services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orbital-space
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80"]
      interval: 5s
      timeout: 5s
      retries: 5
